# Python OOP Exercise

In [1]:
# install tourch
%pip install torch

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.



  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/159.8 MB 2.4 MB/s eta 0:01:06
   ---------------------------------------- 0.5/159.8 MB 6.7 MB/s eta 0:00:24
   ---------------------------------------- 1.6/159.8 MB 11.6 MB/s eta 0:00:14
    --------------------------------------- 3.4/159.8 MB 17.9 MB/s eta 0:00:09
    --------------------------------------- 3.7/159.8 MB 19.5 MB/s eta 0:00:08
   - -------------------------------------- 5.6/159.8 MB 20.9 MB/s eta 0:00:08
   -- ------------------------------------- 8.5/159.8 MB 27.1 MB/s eta 0:00:06
   -- ------------------------------------- 10.2/159.8 MB 27.1 MB/s eta 0:00:06
   -- ------------------------------------- 11.1/159.8 MB 34.4 MB/s eta 0:00:05
   -- ------------------------------------- 11.1/159.8 MB 28.5 MB/s eta 0:00:0

## EX1

In [3]:
import torch
import torch.nn as nn

In [4]:
# Test if torch is installed
x = torch.rand(5, 3)
x

tensor([[0.8989, 0.2306, 0.1002],
        [0.4181, 0.7917, 0.9079],
        [0.7591, 0.3663, 0.6631],
        [0.2509, 0.3397, 0.8473],
        [0.3368, 0.7389, 0.2869]])

In [6]:
# Test softmax function in torch
data = torch.Tensor([1, 2, 3])
softmax = nn.Softmax(dim=0)
print(softmax(data))

tensor([0.0900, 0.2447, 0.6652])


In [7]:
# create my softmax function
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        partition = torch.sum(x_exp)
        return x_exp / partition

my_softmax = MySoftmax()
print(my_softmax(data))


tensor([0.0900, 0.2447, 0.6652])


In [8]:
# create softmax stable function
class MySoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x - torch.max(x))
        partition = torch.sum(x_exp)
        return x_exp / partition

my_softmax_stable = MySoftmaxStable()
print(my_softmax_stable(data))

tensor([0.0900, 0.2447, 0.6652])


## EX2

In [1]:
from abc import ABC, abstractmethod

# Create a class Person with an abstract method describe
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob
    
    def get_yob(self):
        return self.yob
    
    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name:str, yob:int, grade:str):
        super().__init__(name=name, yob=yob)
        self.grade = grade
    
    def describe(self):
        print(f"Student {self.name} was born in {self.yob} and is in grade {self.grade}")

class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        super().__init__(name=name, yob=yob)
        self.subject = subject
    
    def describe(self):
        print(f"Teacher {self.name} was born in {self.yob} and teaches {self.subject}")

class Doctor(Person):
    def __init__(self, name:str, yob:int, specialist:str):
        super().__init__(name=name, yob=yob)
        self.specialist = specialist
    
    def describe(self):
        print(f"Doctor {self.name} was born in {self.yob} and specializes in {self.specialist}")

In [2]:
# Test the classes
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()

teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()

doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

Student studentA was born in 2010 and is in grade 7
Teacher teacherA was born in 1969 and teaches Math
Doctor doctorA was born in 1945 and specializes in Endocrinologists


In [4]:
# Create a class Ward
class Ward:
    def __init__(self, name:str):
        self.name = name
        self.__list_people = list()
    
    def add_person(self, person:Person):
        self.__list_people.append(person)

    def describe(self):
        print(f"List of people in the ward {self.name}")
        for person in self.__list_people:
            person.describe()
    
    def count_doctors(self):
        count = 0
        for person in self.__list_people:
            if isinstance(person, Doctor):
                count += 1
        return count
    
    def sort_age(self):
        self.__list_people.sort(key=lambda x: x.get_yob(), reverse=True)
    
    def compoute_avg_age(self):
        counter = 0
        total_year = 0
        for p in self.__list_people:
            if isinstance(p, Teacher): 
                counter += 1
                total_year += p.get_yob()
        return total_year/counter

In [6]:
# Test the class Ward
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

List of people in the ward Ward1
Student studentA was born in 2010 and is in grade 7
Teacher teacherA was born in 1969 and teaches Math
Teacher teacherB was born in 1995 and teaches History
Doctor doctorA was born in 1945 and specializes in Endocrinologists
Doctor doctorB was born in 1975 and specializes in Cardiologists


In [8]:
# Test the count_doctors method
print(f"\nNumber of doctors: {ward1.count_doctors()}")


Number of doctors: 2


In [9]:
# Test the sort_age method
print("\nAfter sorting Age of Ward1 people")
ward1.sort_age()
ward1.describe()



After sorting Age of Ward1 people
List of people in the ward Ward1
Student studentA was born in 2010 and is in grade 7
Teacher teacherB was born in 1995 and teaches History
Doctor doctorB was born in 1975 and specializes in Cardiologists
Teacher teacherA was born in 1969 and teaches Math
Doctor doctorA was born in 1945 and specializes in Endocrinologists


In [11]:
# Test the compute_average method
print(f"\nAverage year of birth (teachers): {ward1.compoute_avg_age()}")


Average year of birth (teachers): 1982.0


## EX3

In [12]:
class Stack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.stack = []

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity

    def pop(self):
        if not self.is_empty():
            return self.stack.pop()
        else:
            return "Stack is empty"

    def push(self, value):
        if not self.is_full():
            self.stack.append(value)
        else:
            return "Stack is full"

    def top(self):
        if not self.is_empty():
            return self.stack[-1]
        else:
            return "Stack is empty"

In [13]:
#  Test the Stack class

stack1 = Stack(capacity=5)

stack1.push(1)

stack1.push(2)

print(stack1.is_full())

print(stack1.top())

print(stack1.pop())

print(stack1.top())

print(stack1.pop())

print(stack1.is_empty())

False
2
2
1
1
True


In [ ]:
# Test the Stack class

stack2 = Stack(capacity=2)

stack2.push(1)

stack2.push(2)

print(stack2.top())

print(stack2.is_full())

print(stack2.pop())

print(stack2.pop())

print(stack2.is_empty())

print(stack2.pop())